@baseUrl = https://etand.se:16443
@testClinic = 9002

### Retrieve therapist regardless of treatment type
# 1. Login - Authenticate user with credentials
# 2. Get Therapists - Retrieve available therapists independent of treatment type
# 3. Logout - Terminate the session
#
# Calls: 
#   /api/v1/login 
#   /tdl/v1/behandlare (with behandlingstypKod = "") 
#   /api/v1/logout 

### Login - get accessKod
# @name login_all_therapists
POST {{baseUrl}}/api/v1/login
Content-Type: application/json

{
  "almasoftKund": {{testClinic}},
  "integratorKod": "{{integratorKod}}",
  "integratorLosen": "{{integratorLosen}}"
}

### Get All Therapists
POST {{baseUrl}}/tdl/v1/behandlare
Content-Type: application/json

{
  "almasoftKund": {{testClinic}},
  "integratorKod": "{{integratorKod}}",
  "accessKod": "{{login_all_therapists.response.body.accessKod}}",
  "behandlingstypKod": ""
}

### Logout
POST {{baseUrl}}/api/v1/logout
Content-Type: application/json

{
  "almasoftKund": {{testClinic}},
  "integratorKod": "{{integratorKod}}",
  "accessKod": "{{login_all_therapists.response.body.accessKod}}"
}


### Retrieve therapists for a certain treatment type
# 1. Login - Authenticate user with credentials
# 2. Get all treatment types - Retrieve available treatment types independent of therapist
# 3. Get Therapists - Retrieve therapists for a specific treatment type
# 4. Logout - Terminate the session
#
# Calls:
#   /api/v1/login
#   /tdl/v1/behandlingstyper (with behandlareKod = "")
#   /tdl/v1/behandlare (with behandlingstypKod = "<ID from behandlingstyper call>")
#   /api/v1/logout

### Login - get accessKod for treatment type
# @name login_specific_treatment
POST {{baseUrl}}/api/v1/login
Content-Type: application/json

{
  "almasoftKund": {{testClinic}},
  "integratorKod": "{{integratorKod}}",
  "integratorLosen": "{{integratorLosen}}"
}

### Get Treatment Types
# @name get_treatment_types
POST {{baseUrl}}/tdl/v1/behandlingstyper
Content-Type: application/json
  
{
  "almasoftKund": {{testClinic}},
  "integratorKod": "{{integratorKod}}",
  "accessKod": "{{login_specific_treatment.response.body.accessKod}}",
  "behandlareKod": ""
}

### Get Therapists by Treatment Type
POST {{baseUrl}}/tdl/v1/behandlare
Content-Type: application/json

{
  "almasoftKund": {{testClinic}},
  "integratorKod": "{{integratorKod}}",
  "accessKod": "{{login_specific_treatment.response.body.accessKod}}",
  "behandlingstypKod": "{{get_treatment_types.response.body.behandlingstyper[0].kod}}"
}

### Logout
POST {{baseUrl}}/api/v1/logout
Content-Type: application/json

{
  "almasoftKund": {{testClinic}},
  "integratorKod": "{{integratorKod}}",
  "accessKod": "{{login_specific_treatment.response.body.accessKod}}"
}